### ISSUE TITLE
如何导出不同学期的课表

### ISSUE THREAD

**Issue by yjn140** [Zxilly/CalenderGenerator#5]
我发现导出的课表是当前默认学期的课表。怎么样修改才能导出其他学期的。

**Comment by Zxilly** [comment]
https://github.com/Zxilly/CalendarGenerator/blob/9d07a1f62b11f6c3486edf77a66deada75e9bce3/func.py#L69-L72
改这里，不过下学期的课不一定全了，急啥

**Comment by yjn140** [comment]
ok

**Comment by yjn140** [comment]
嗯好
